const cover=document.querySelector('#cover');const musicBtn=document.querySelector('#musicToggle');const music=document.querySelector('#weddingMusic');let playing=false;
const params=new URLSearchParams(location.search);const invitedName=(params.get('to')||params.get('tamu')||'Tamu Undangan').trim().slice(0,80);document.querySelector('#guestName').textContent=invitedName;document.title=`Undangan untuk ${invitedName} — Awfy & Nana`;const nameInput=document.querySelector('input[name="name"]');if(invitedName!=='Tamu Undangan'){nameInput.value=invitedName;nameInput.readOnly=true;}
async function startMusic(){if(playing)return;try{music.volume=.45;await music.play();playing=true;musicBtn.classList.add('playing');musicBtn.textContent='♫'}catch{notify('Ketuk tombol musik sekali lagi untuk memutar lagu')}}
function stopMusic(){music.pause();playing=false;musicBtn.classList.remove('playing');musicBtn.textContent='♪'}
document.querySelector('#openInvitation').addEventListener('click',()=>{cover.classList.add('hide');document.body.classList.remove('locked');startMusic();setTimeout(()=>cover.remove(),900)});musicBtn.addEventListener('click',()=>playing?stopMusic():startMusic());
const target=new Date('2026-12-20T08:00:00+07:00');function tick(){const d=Math.max(0,target-new Date()),v=[Math.floor(d/864e5),Math.floor(d/36e5)%24,Math.floor(d/6e4)%60,Math.floor(d/1e3)%60];['days','hours','minutes','seconds'].forEach((id,i)=>document.querySelector('#'+id).textContent=String(v[i]).padStart(2,'0'))}tick();setInterval(tick,1000);
const toast=document.querySelector('#toast');function notify(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}document.querySelectorAll('.copy-btn').forEach(b=>b.addEventListener('click',async()=>{await navigator.clipboard.writeText(b.dataset.copy);notify('Nomor rekening berhasil disalin')}));
document.querySelector('#calendarBtn').addEventListener('click',()=>{const data='BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:20261220T010000Z\nDTEND:20261220T070000Z\nSUMMARY:Pernikahan Awfy & Nana\nLOCATION:The Glass House Jakarta\nDESCRIPTION:Akad dan resepsi pernikahan Awfy dan Nana\nEND:VEVENT\nEND:VCALENDAR',a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/calendar'}));a.download='Pernikahan-Awfy-Nana.ics';a.click();URL.revokeObjectURL(a.href)});
const dialog=document.querySelector('#lightbox'),lightbox=document.querySelector('#lightboxImage');document.querySelectorAll('#gallery button').forEach(b=>b.addEventListener('click',()=>{lightbox.src=b.querySelector('img').src;dialog.showModal()}));document.querySelector('#closeLightbox').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.querySelector('#rsvpForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),name=fd.get('name'),msg=fd.get('message'),initial=name.trim()[0]?.toUpperCase()||'T';const article=document.createElement('article');article.innerHTML=`<div>${initial}</div><p><b></b><span></span></p>`;article.querySelector('b').textContent=name;article.querySelector('span').textContent=msg;document.querySelector('#wishes').prepend(article);document.querySelector('#formStatus').textContent='Terima kasih, konfirmasi dan ucapan Anda sudah tersimpan di perangkat ini.';e.currentTarget.reset()});
